[build]
target = "xtensa-esp32s3-none-elf"

[target.'cfg(all(target_arch = "riscv", target_os = "none"))']
linker = "ldproxy"
runner = "probe-rs run --chip esp32s3"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.3"
